name    'leonardothibes-usvn'
author  'leonardothibes'
version '1.0.0'
license 'MIT'
summary 'A puppet module to install usvn subversion management tool'
description 'A puppet module to install usvn subversion management tool'
source 'git://github.com/leonardothibes/puppet-usvn.git'
project_page 'http://github.com/leonardothibes/puppet-usvn'
